# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

favicon: "logo.png"

appearance:
  theme_day: minimal
  theme_night: minimal
  font: minimal
  font_size: L

logo:
  main: "logo.png"
  alt: "UFHCC Bioinformatics Logo"
  show_logo: true

# SEO

marketing:
  seo:
    site_type: Project
    local_business_type: ''
    org_name: 'UF Health Cancer Center Bioinformatics'
    description: "Bioinformatics Unit Hub"
    twitter: ''
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    google_tag_manager: ''
    microsoft_clarity: ''
  verification:
    google: ''
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: true

footer:
  copyright:
    notice: '© 2025 UF Health Cancer Center Bioinformatics. Portions adapted from the [Weecology Wiki](https://wiki.weecology.org/) by Weecology, used 
under [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/).'
    powered_by: 'Published with [Hugo Blox Builder](https://hugoblox.com/) — the free, [open source](https://github.com/HugoBlox/hugo-blox-builder) 
website builder.'

# Localization

locale:
  date_format: '2006-01-02'
  time_format: '3:04 PM'

# Site features

features:
  syntax_highlighter:
    theme_light: github-light
    theme_dark: dracula
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/UFHCC-BCBSR/res-hub'
    content_dir: content
    branch: main
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
    giscus:
      repo: ''
      repo_id: ''
      category: ''
      category_id: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
